services:
  miniex-blog:
    build:
       context: .
       dockerfile: Dockerfile
    container_name: "miniex_blog"

    restart: always

    ports:
      - "1280:80"

    volumes:
      - ./assets:/app/assets
      - ./templates:/app/templates
      - ./contents:/app/contents

    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1

    command: ["./blog"]

    networks:
      - reverse_proxy 

networks:
  reverse_proxy:
    name: "n0000-reverse_proxy"
    external: true
